# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish

on:
  push:
    branches:
    - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@pushpender-singh-ap'
      - run: npm i
      - name: Bump version and push tag
        id: tag
        uses: anothrNick/github-tag-action@1.17.2
        env:
          GITHUB_TOKEN: ${{ secrets.GIT }}
          NPM_TOKEN: ${{ secrets.NPM }}
          WITH_V: true
          RELEASE_BRANCHES: master
          DEFAULT_BUMP: patch
      - name: version
        run: npm --no-git-tag-version --allow-same-version version ${{ steps.tag.outputs.tag }}
      - name: publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GIT }}
          NPM_TOKEN: ${{ secrets.NPM }}
