name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '10.x'
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: 82043ad4-efa0-4250-9e10-7f6ee7e3fe78
        registry-url: 'https://registry.npmjs.org'
    - uses: actions/setup-node@v2
      with:
        registry-url: 'https://npm.pkg.github.com'
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: 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
